_target_: data.copying.Copying.create_split_datasets
use_validation: true
path: ./datastorage/copying
max_length: 50
shuffle: true
vocab_size: 40
sequence_length: 512,20,8192 # train, test_start, test_stop
num_samples: 300000,1 # train samples, test samples
create_artificial_datasets: true
